extends Node

enum PetState {ROAMING, FEEDING, MENU, EVOLVING}
enum Personality {MEAN, CALM, FOCUSED, AIRHEAD}
enum AbilityStat {POW, END, SPD, BAL}
enum InputType {LEFTBUTTON, MIDDLEBUTTON, RIGHTBUTTON}

enum DeviceButton {CENTER_BUTTON, LEFT_BUTTON, RIGHT_BUTTON, 
					MINIMIZE_BUTTON, BORDER_BUTTON, OPTIONS_BUTTON, POWER_BUTTON}
